/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GlobalCounter
 */
export interface GlobalCounter {
    /**
     * 
     * @type {number}
     * @memberof GlobalCounter
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof GlobalCounter
     */
    readonly count: number;
    /**
     * 
     * @type {Date}
     * @memberof GlobalCounter
     */
    readonly lastUpdated: Date;
}

/**
 * Check if a given object implements the GlobalCounter interface.
 */
export function instanceOfGlobalCounter(value: object): value is GlobalCounter {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    return true;
}

export function GlobalCounterFromJSON(json: any): GlobalCounter {
    return GlobalCounterFromJSONTyped(json, false);
}

export function GlobalCounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalCounter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'count': json['count'],
        'lastUpdated': (new Date(json['last_updated'])),
    };
}

export function GlobalCounterToJSON(value?: Omit<GlobalCounter, 'id'|'count'|'last_updated'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

