/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Nested
 */
export interface Nested {
    /**
     * 
     * @type {number}
     * @memberof Nested
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Nested
     */
    title: string;
}

/**
 * Check if a given object implements the Nested interface.
 */
export function instanceOfNested(value: object): value is Nested {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function NestedFromJSON(json: any): Nested {
    return NestedFromJSONTyped(json, false);
}

export function NestedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Nested {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
    };
}

export function NestedToJSON(value?: Omit<Nested, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
    };
}

