/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * 
     * @type {Array<number>}
     * @memberof Order
     */
    readonly items: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    ordered?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Order
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Array<number>}
     * @memberof Order
     */
    payment: Array<number>;
}

/**
 * Check if a given object implements the Order interface.
 */
export function instanceOfOrder(value: object): value is Order {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('payment' in value) || value['payment'] === undefined) return false;
    return true;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'],
        'ordered': json['ordered'] == null ? undefined : json['ordered'],
        'createdAt': (new Date(json['created_at'])),
        'payment': json['payment'],
    };
}

export function OrderToJSON(value?: Omit<Order, 'items'|'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ordered': value['ordered'],
        'payment': value['payment'],
    };
}

