/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    item: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    order: number;
}

/**
 * Check if a given object implements the OrderItem interface.
 */
export function instanceOfOrderItem(value: object): value is OrderItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('item' in value) || value['item'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function OrderItemFromJSON(json: any): OrderItem {
    return OrderItemFromJSONTyped(json, false);
}

export function OrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'item': json['item'],
        'order': json['order'],
    };
}

export function OrderItemToJSON(value?: Omit<OrderItem, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'quantity': value['quantity'],
        'item': value['item'],
        'order': value['order'],
    };
}

