/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedOrder
 */
export interface PatchedOrder {
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedOrder
     */
    readonly items?: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedOrder
     */
    ordered?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedOrder
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedOrder
     */
    payment?: Array<number>;
}

/**
 * Check if a given object implements the PatchedOrder interface.
 */
export function instanceOfPatchedOrder(value: object): value is PatchedOrder {
    return true;
}

export function PatchedOrderFromJSON(json: any): PatchedOrder {
    return PatchedOrderFromJSONTyped(json, false);
}

export function PatchedOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : json['items'],
        'ordered': json['ordered'] == null ? undefined : json['ordered'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'payment': json['payment'] == null ? undefined : json['payment'],
    };
}

export function PatchedOrderToJSON(value?: Omit<PatchedOrder, 'items'|'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ordered': value['ordered'],
        'payment': value['payment'],
    };
}

