/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedGlobalCounter
 */
export interface PatchedGlobalCounter {
    /**
     * 
     * @type {number}
     * @memberof PatchedGlobalCounter
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedGlobalCounter
     */
    readonly count?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedGlobalCounter
     */
    readonly lastUpdated?: Date;
}

/**
 * Check if a given object implements the PatchedGlobalCounter interface.
 */
export function instanceOfPatchedGlobalCounter(value: object): value is PatchedGlobalCounter {
    return true;
}

export function PatchedGlobalCounterFromJSON(json: any): PatchedGlobalCounter {
    return PatchedGlobalCounterFromJSONTyped(json, false);
}

export function PatchedGlobalCounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedGlobalCounter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'count': json['count'] == null ? undefined : json['count'],
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
    };
}

export function PatchedGlobalCounterToJSON(value?: Omit<PatchedGlobalCounter, 'id'|'count'|'last_updated'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

