/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedOrderItem
 */
export interface PatchedOrderItem {
    /**
     * 
     * @type {number}
     * @memberof PatchedOrderItem
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedOrderItem
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedOrderItem
     */
    item?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedOrderItem
     */
    order?: number;
}

/**
 * Check if a given object implements the PatchedOrderItem interface.
 */
export function instanceOfPatchedOrderItem(value: object): value is PatchedOrderItem {
    return true;
}

export function PatchedOrderItemFromJSON(json: any): PatchedOrderItem {
    return PatchedOrderItemFromJSONTyped(json, false);
}

export function PatchedOrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedOrderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'item': json['item'] == null ? undefined : json['item'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function PatchedOrderItemToJSON(value?: Omit<PatchedOrderItem, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'quantity': value['quantity'],
        'item': value['item'],
        'order': value['order'],
    };
}

