/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedAddress
 */
export interface PatchedAddress {
    /**
     * 
     * @type {number}
     * @memberof PatchedAddress
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    zipCode?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedAddress
     */
    order?: number;
}

/**
 * Check if a given object implements the PatchedAddress interface.
 */
export function instanceOfPatchedAddress(value: object): value is PatchedAddress {
    return true;
}

export function PatchedAddressFromJSON(json: any): PatchedAddress {
    return PatchedAddressFromJSONTyped(json, false);
}

export function PatchedAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'address': json['address'] == null ? undefined : json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function PatchedAddressToJSON(value?: Omit<PatchedAddress, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'city': value['city'],
        'state': value['state'],
        'zip_code': value['zipCode'],
        'order': value['order'],
    };
}

