/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedPayment
 */
export interface PatchedPayment {
    /**
     * 
     * @type {number}
     * @memberof PatchedPayment
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedPayment
     */
    stripeChargeId?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedPayment
     */
    amount?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedPayment
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatchedPayment
     */
    order?: number;
}

/**
 * Check if a given object implements the PatchedPayment interface.
 */
export function instanceOfPatchedPayment(value: object): value is PatchedPayment {
    return true;
}

export function PatchedPaymentFromJSON(json: any): PatchedPayment {
    return PatchedPaymentFromJSONTyped(json, false);
}

export function PatchedPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stripeChargeId': json['stripe_charge_id'] == null ? undefined : json['stripe_charge_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function PatchedPaymentToJSON(value?: Omit<PatchedPayment, 'id'|'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stripe_charge_id': value['stripeChargeId'],
        'amount': value['amount'],
        'order': value['order'],
    };
}

