/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Nested } from './Nested';
import {
    NestedFromJSON,
    NestedFromJSONTyped,
    NestedToJSON,
} from './Nested';

/**
 * 
 * @export
 * @interface PatchedItem
 */
export interface PatchedItem {
    /**
     * 
     * @type {number}
     * @memberof PatchedItem
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedItem
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedItem
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedItem
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedItem
     */
    image?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedItem
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Nested}
     * @memberof PatchedItem
     */
    readonly category?: Nested;
}

/**
 * Check if a given object implements the PatchedItem interface.
 */
export function instanceOfPatchedItem(value: object): value is PatchedItem {
    return true;
}

export function PatchedItemFromJSON(json: any): PatchedItem {
    return PatchedItemFromJSONTyped(json, false);
}

export function PatchedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'image': json['image'] == null ? undefined : json['image'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'category': json['category'] == null ? undefined : NestedFromJSON(json['category']),
    };
}

export function PatchedItemToJSON(value?: Omit<PatchedItem, 'id'|'created_at'|'category'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'price': value['price'],
        'image': value['image'],
    };
}

