/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUserProfile
 */
export interface PatchedUserProfile {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserProfile
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserProfile
     */
    stripeCustomerId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUserProfile
     */
    oneClickPurchasing?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserProfile
     */
    user?: number;
}

/**
 * Check if a given object implements the PatchedUserProfile interface.
 */
export function instanceOfPatchedUserProfile(value: object): value is PatchedUserProfile {
    return true;
}

export function PatchedUserProfileFromJSON(json: any): PatchedUserProfile {
    return PatchedUserProfileFromJSONTyped(json, false);
}

export function PatchedUserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stripeCustomerId': json['stripe_customer_id'] == null ? undefined : json['stripe_customer_id'],
        'oneClickPurchasing': json['one_click_purchasing'] == null ? undefined : json['one_click_purchasing'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function PatchedUserProfileToJSON(value?: Omit<PatchedUserProfile, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stripe_customer_id': value['stripeCustomerId'],
        'one_click_purchasing': value['oneClickPurchasing'],
        'user': value['user'],
    };
}

