/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    stripeChargeId: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    amount: string;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    order: number;
}

/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('stripeChargeId' in value) || value['stripeChargeId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'stripeChargeId': json['stripe_charge_id'],
        'amount': json['amount'],
        'createdAt': (new Date(json['created_at'])),
        'order': json['order'],
    };
}

export function PaymentToJSON(value?: Omit<Payment, 'id'|'created_at'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stripe_charge_id': value['stripeChargeId'],
        'amount': value['amount'],
        'order': value['order'],
    };
}

