/* tslint:disable */
/* eslint-disable */
/**
 * Shop Project API
 * Just playing around with Django
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    stripeCustomerId: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfile
     */
    oneClickPurchasing?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    user: number;
}

/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('stripeCustomerId' in value) || value['stripeCustomerId'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'stripeCustomerId': json['stripe_customer_id'],
        'oneClickPurchasing': json['one_click_purchasing'] == null ? undefined : json['one_click_purchasing'],
        'user': json['user'],
    };
}

export function UserProfileToJSON(value?: Omit<UserProfile, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stripe_customer_id': value['stripeCustomerId'],
        'one_click_purchasing': value['oneClickPurchasing'],
        'user': value['user'],
    };
}

